<!DOCTYPE html>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags" %>
<html lang="en">

<body>
<%-- <h1>${message}</h1>--%>


<table border="1">
    <caption>SharedMemory2</caption>
    <tr>
        <th>KEY</th>
        <th>SHM ID</th>
        <th>Permission</th>
        <th>Size</th>
        <th>Proc number</th>
        <th>Last Att, Det</th>
        <th>Type</th>
        <th>Owner</th>
    </tr>
    <c:forEach var="item" items="${sharedMemoryList}">
    <tr><td><c:out value="${item.getKey()}"/></td>
        <td>SHM ID</td>
        <td>Permission</td>
        <td>Size</td>
        <td>Proc number</td>
        <td>Last Att, Det</td>
        <td>Type</td>
        <td>Owner</td>
    </tr>
    </c:forEach>
</table>
<%--<p><a href="${springUrl}">URL generated by Spring"${array}"</a></p>
<p><a href="${url}">URL generated by JSTL</a></p>
<c:forEach var="item" items="${array}">
    item <c:out value="${item}"></c:out>
</c:forEach>--%>
</body>

</html>