<!DOCTYPE html>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags" %>
<html lang="en">

<body>
<%-- <h1>${message}</h1>--%>


<table border="1">
    <caption>Terminal</caption>
    <tr>
        <th>Terminal ID</th>
        <th>Terminal type</th>
        <th>Current node</th>
        <th>Connection time</th>
        <th>Previous node</th>
        <th>Owning nodes</th>
        <th>statuses</th>
    </tr>
    <c:forEach var="item" items="${terminalList}">
    <tr><td><c:out value="${item.getTerminalID()}"/></td>
        <td>SHM ID</td>
        <td>Permission</td>
        <td>Size</td>
        <td>Proc number</td>
        <td>Last Att, Det</td>
        <td>Type</td>
        <td>Owner</td>
    </tr>
    </c:forEach>
</table>
<%--<p><a href="${springUrl}">URL generated by Spring"${array}"</a></p>
<p><a href="${url}">URL generated by JSTL</a></p>
<c:forEach var="item" items="${array}">
    item <c:out value="${item}"></c:out>
</c:forEach>--%>
</body>

</html>