<!DOCTYPE html>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags" %>
<%--<%@ taglib prefix="spring" uri="http://www.springframework.org/tags/form" %>--%>
<html lang="en">

<head>
    <title>Index Page</title>
</head>
<body>
<%-- <h1>${message}</h1>--%>


<%--
<button type="button" onclick="loadDoc()">Change Content</button>
--%>

<script>
    function loadDoc(url, elementId) {
        var xhttp = new XMLHttpRequest();
        xhttp.onreadystatechange = function() {
            if (xhttp.readyState == 4 && xhttp.status == 200) {
                document.getElementById(elementId).innerHTML = xhttp.responseText;
            }
        };
        xhttp.open("GET", url, true);
        xhttp.send();
    }
</script>
<table>
    <tr>
        <td><button type="button" onclick="loadDoc('/getSharedMemory', 'table')">Shared memory</button></td>
        <td><button type="button" onclick="loadDoc('/getSemaphores', 'table')">Semaphores</button></td>
        <td><button type="button" onclick="loadDoc('/getIPCQueue', 'table')">IPC queues</button></td>
        <td><button type="button" onclick="loadDoc('/getTerminal', 'table')">Terminals</button></td>
    </tr>
    <tbody>
    <tr>
        <td colspan="4"><div id="table"></div></td>
    </tr>
    </tbody>
</table>

<%--<%@include file="getSemaphores.jsp"%>
<jsp:include page="getSemaphores.jsp" flush="true"></jsp:include>--%>
<%--<jsp:forward page="getIPCQueue.jsp"></jsp:forward>
<iframe content=""></iframe>
<%@include file="getTerminal.jsp"%>--%>

<%--<p><a href="${springUrl}">URL generated by Spring"${array}"</a></p>
<p><a href="${url}">URL generated by JSTL</a></p>
<c:forEach var="item" items="${array}">
    item <c:out value="${item}"></c:out>
</c:forEach>--%>
</body>

</html>